apiVersion: v1
data:
  .env: |
    HOST_PORTAL=https://portal.cms.assembly.govstack.global
    HOST_INSTITUTION=https://institution.cms.assembly.govstack.global
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{".env":"HOST_PORTAL=https://portal.cms.assembly.govstack.global\nHOST_INSTITUTION=https://institution.cms.assembly.govstack.global\n"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"app-dotenv","namespace":"cms-system"}}
  creationTimestamp: "2025-10-27T22:19:00Z"
  name: app-dotenv
  namespace: cms-system
  resourceVersion: "5318245"
  uid: 29746c98-6824-4931-8fb1-83d2506cfc45
