page:
  logo:
    file: 'EXT:sitepackage/Resources/Public/Institution/Images/Logo/logo_dtec.svg'
    height: 80
    linktitle: 'LLL:EXT:sitepackage/Resources/Private/Language/locallang.xlf:site.title'
    alt: 'LLL:EXT:sitepackage/Resources/Private/Language/locallang.xlf:site.title'
  theme:
    search:
      targetPid: 16
    footer:
      contactPid: 14
indexedsearch:
  rootPidList: 1
  targetPid: 16
